# Frame config
frame:
  width: 720
  height: 480  # NTSC

# Reed-Solomon config
rs:
  use_for_headers: true
  use_for_data: false
  ecc_symbols: 50
  chunk_bytes: 150

# PRBS config
prbs:
  use_for_headers: true
  use_for_data: false
  chip_length_for_headers: 3
  chip_length_for_data: 1
  data_prbs_poly: [8, 2]

# Length block config
length:
  bits_per_field: 32
  chip_length: 7

# Marker codewords config
markers:
  use: true
  codeword_len: 64
  det_thresh: 0.80

# Camera / input config
camera:
  input_source: camera  # camera or file
  camera_index: 0
  target_fps: 25.0
  path_to_video: "/home/matan/Documents/matan/D2A2D/1572378-sd_960_540_24fps.mp4"

# Noise for demo GUI
noise:
  gauss_noise: 50.0

# JPEG compression config
jpeg:
  quality: 70
  rst_interval: 10
  header_template_b64: "/9j/4AAQSkZJRgABAQAAAQABAAD/2wBDAAoHBwgHBgoICAgLCgoLDhgQDg0NDh0VFhEYIx8lJCIfIiEmKzcvJik0KSEiMEExNDk7Pj4+JS5ESUM8SDc9Pjv/2wBDAQoLCw4NDhwQEBw7KCIoOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozv/wAARCAHgAtADASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/90ABAAK/9oADAMBAAIRAxEAPwA="

# Runtime collection config
runtime:
  save: false
  os: raspberry_pi  # windows or raspberry_pi
  start_frame: 5
  num_frames: 10

